#!/usr/bin/env bash
# displays infinity and beyond with sleep 2 in between with each iteration

trap sigtrap 15
sigtrap()
{
    echo "I am invincible!!!"
}
while ((1))
do
    echo "To infinity and beyond"
    sleep 2
done
