#!/usr/bin/env bash
# Repeat's "Best School" 10 times using while loops.
# Loops from 1 to 10 and displays:
#   "bad luck" for the 4th iteration
#   "good luck" for the 8th iteration
#   "Best School" for all other iterations

counter=0

while [ $counter -lt 10 ]
do
  if [ $counter -eq 3 ]
  then
    echo "bad luck"
  elif [ $counter -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( counter++ ))
done
