#!/usr/bin/env bash
# Repeat numbers from 1 to 20 in addition to:
# "bad luck from china" for the 4h loop iteration
# "bad luck from Japan" for the 9th loop iteration
# "bad luck from Italy" for the 17 loop iteration

counter=1

while [ $counter -le 20 ]
do
  echo "$counter"
  case $counter in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( counter++ ))
done
