#!/usr/bin/env bash
# Displays all information about the file "school".
#  tell's
#    if the file exists
#    if the file is empty or not 


if [ -e "school" ]
then
  echo "school file exists"
  if [ -s "school" ]
  then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi

  if [ -f "school" ]
  then
    echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi
