#!/usr/bin/env bash
# Requirements:

# * localhost resolves to 127.0.0.2
# * facebook.com resolves to 8.8.8.8./usr/bin/env bash

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
sed -i "\$a8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
