#!/usr/bin/env bash
# Write a Bash Script that displays all active IPv4 IPs on the machine it's executed on.
# Example
# ./1-show_attached_IPs
# * 10.0.2.15
# * 127.0.0.1

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 6-
